print("Testing error ....")
print("Testing from trig....")
local m = io.popen("make build")
print(m:read("*a"))
m:close()
print("Done")
print(string.format("Type: %s", trig.Type))
print(string.format("Path: %s", trig.Data["path"]))
print(string.format("Operation: %s", trig.Data["op"]))
